### ISSUE TITLE
If the stratum0 is down, the script fails.

### ISSUE THREAD

**Issue by terjekv** [EESSI/status-page#4]
The script tries to compare versions (and other data) of the repos to the same data on stratum0. When stratum0 is down, the script dies.

**Comment by terjekv** [comment]
`````
[eessi@monitoring ~]$ /usr/local/bin/cvmfs_server_scraper_exporter.py
http://rug-nl.stratum0.cvmfs.eessi-infra.org/cvmfs/data.eessi-hpc.org/.cvmfspublished <urlopen error timed out>
http://rug-nl.stratum0.cvmfs.eessi-infra.org/cvmfs/data.eessi-hpc.org/.cvmfs_status.json <urlopen error timed out>
http://rug-nl.stratum0.cvmfs.eessi-infra.org/cvmfs/pilot.eessi-hpc.org/.cvmfspublished <urlopen error timed out>
http://rug-nl.stratum0.cvmfs.eessi-infra.org/cvmfs/pilot.eessi-hpc.org/.cvmfs_status.json <urlopen error timed out>
Traceback (most recent call last):
  File "/usr/local/bin/cvmfs_server_scraper_exporter.py", line 98, in <module>
    main()
  File "/usr/local/bin/cvmfs_server_scraper_exporter.py", line 95, in main
    metrics.run_metrics_loop()
  File "/usr/local/bin/cvmfs_server_scraper_exporter.py", line 52, in run_metrics_loop
    current_repo_stratum0_revisions[repo.name] = repo.revision
AttributeError: 'Repository' object has no attribute 'revision'

`````
